version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=afcens
    - MYSQL_DATABASE=afcens
    - MYSQL_USER=afcens
    - MYSQL_PASSWORD=afcens
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  afcens-visualizer:
    build: visualizer
    command: ${afcens_SETTINGS}
    ports:
    - "8080:8080"
    - "8081:8081"
    - "8082:8082"

  afcens-simulator:
    build: simulator

  elasticsearch:
    image: elasticsearch:6.8.3
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  mysql-data:
  redis-data:
  elasticsearch-data:

